test_namespace:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      use_sim_time: true
      
      # Definition of the joint state broadcaster controller  
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      # Definition of the joint trajectory controller
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      
  joint_trajectory_controller:
    ros__parameters:
        
        # Definition of all the controlled joints 
        joints:
          - joint_1.2
          - joint_2.3
          - joint_3.4
          - joint_4.5
          - joint_5.6
          - joint_6.7
          - joint_EE.Lgripper
          
        interface_name: position

        command_interfaces:
          - position
    
        state_interfaces:
          - position
          - velocity

        state_publish_rate: 50.0 # Defaults to 50
        action_monitor_rate: 20.0 # Defaults to 20

        allow_partial_joints_goal: true # Defaults to false
        hardware_state_has_offset: true
        deduce_states_from_derivatives: true
    
        constraints:
          stopped_velocity_tolerance: 0.01 # Defaults to 0.01
          goal_time: 0.0 # Defaults to 0.0 (start immediately)
